
version: '3.7'

services:

    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    #  MONGO DB
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    db:
        image: mongo:4.2
        container_name: mr-owlf-mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: mr-owlf-db
        ports:
            - 27017:27017
        volumes:
            - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    #  DATA STREAM SERVICES
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~= 
    dss:
        image: mr-owlf-dss:latest
        container_name: mr-owlf-dss
        depends_on:
            - db
        environment:
            APP_DB_CONN: db
            APP_DB_PORT: "27017"
            APP_DB_NAME: "mr-owlf-db"
            APP_DB_USER: "dss"
            APP_DB_PASSWORD: "D4t4SS"
            APP_LOG_LEVEL: "INFO"

    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    #  MACHINE LEARNING SERVICES
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~= 
    mls:
        image: mr-owlf-mls:latest
        container_name: mr-owlf-mls
        depends_on:
            - db
        environment:
            APP_INITIAL_DELAY: 300
            APP_DB_CONN: db
            APP_DB_PORT: "27017"
            APP_DB_NAME: "mr-owlf-db"
            APP_DB_USER: "mls"
            APP_DB_PASSWORD: "ML34rn"
            APP_LOG_LEVEL: "INFO"
            APP_CLF_FILE: "/shared/classifier.pkl"
            APP_VECTORIZER_FILE: "/shared/vectorizer.pkl"
        volumes:
            - ./.shared:/shared/

    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    #  API
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~= 
    api:
        image: mr-owlf-api:latest
        container_name: mr-owlf-api
        restart: always
        depends_on:
            - db
        ports:
            - 80:80
        environment:
            APP_DB_CONN: db
            APP_DB_PORT: "27017"
            APP_DB_NAME: "mr-owlf-db"
            APP_DB_USER: "api"
            APP_DB_PASSWORD: "4P1"
            APP_LOG_LEVEL: "INFO"
            APP_CLF_FILE: "/shared/classifier.pkl"
            APP_VECTORIZER_FILE: "/shared/vectorizer.pkl"
        volumes:
            - ./.shared:/shared/
 

