
version: '3.7'

services:

    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    #  MONGO DB
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    db:
        image: mongo:latest
        container_name: mr-owlf-mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: mr-owlf-db
        ports:
            - 27017:27017
        volumes:
            - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    #  DATA STREAM SERVICES
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~= 
    dss:
        image: mr-owlf-dss
        container_name: mr-owlf-dss
        # restart: always
        depends_on:
            - db
        environment:
            MR_OWLF_ENV: "DOCKER"
            MR_OWLF_LOG_FILE: "/usr/src/mr-owlf/logs/mr-owlf-dss.log"
            MR_OWLF_DB_CONN: db
            MR_OWLF_DB_PORT: "27017"
            MR_OWLF_DB_NAME: "mr-owlf-db"
            MR_OWLF_DB_USER: "dss"
            MR_OWLF_DB_PASSWORD: "D4t4SS"
        volumes:
            - ./.shared/logs:/usr/src/mr-owlf/logs/

    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    #  MACHINE LEARNING SERVICES
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~= 
    mls:
        image: mr-owlf-mls
        container_name: mr-owlf-mls
        # restart: always
        depends_on:
            - db
        environment:
            MR_OWLF_ENV: "DOCKER"
            MR_OWLF_LOG_FILE: "/usr/src/mr-owlf/logs/mr-owlf-mls.log"
            MR_OWLF_DB_CONN: db
            MR_OWLF_DB_PORT: "27017"
            MR_OWLF_DB_NAME: "mr-owlf-db"
            MR_OWLF_DB_USER: "mls"
            MR_OWLF_DB_PASSWORD: "ML34rn"
            MR_OWLF_CLF_FILE: "/usr/src/mr-owlf/shared/clf.pkl"
        volumes:
            - ./.shared:/usr/src/mr-owlf/shared/
            - ./.shared/logs:/usr/src/mr-owlf/logs/

    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    #  API
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~= 
    api:
        image: mr-owlf-api
        container_name: mr-owlf-api
        restart: always
        ports:
            - 80:80
        environment:
            MR_OWLF_CLF_FILE: "/usr/src/mr-owlf/shared/clf.pkl"
        volumes:
            - ./.shared:/usr/src/mr-owlf/shared/
 

