
version: '3.7'

services:

    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    #  CASSANDRA: NODE 01
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    cassandra-node-01:
        image: cassandra:3.11
        container_name: cassandra-node-01
        volumes:
            - ./.data/node-01:/var/lib/cassandra/data
            - ./cassandra/init.cql:/app/init-cassandra.cql
        ports:
            - 9042:9042
        environment:
            - CASSANDRA_START_RPC=true
            - CASSANDRA_CLUSTER_NAME=mr-owlf-cluster
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=mr-owlf-datacenter
    
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    #  DATA STREAM SERVICES
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~= 
    dss:
        image: mr-owlf-dss
        container_name: mr-owlf-dss
        # restart: always
        depends_on:
            - cassandra-node-01
        environment:
            MR_OWLF_ENV: "DOCKER"
            MR_OWLF_LOG_FILE: "/usr/src/mr-owlf/logs/mr-owlf-dss.log"
            MR_OWLF_DB_CONN: cassandra-node-01
            MR_OWLF_DB_PORT: "9042"
            MR_OWLF_DB_KEYSPACE: "mr_owlf_ks"
        volumes:
            - ./.shared/logs:/usr/src/mr-owlf/logs/

    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    #  MACHINE LEARNING SERVICES
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~= 
    mls:
        image: mr-owlf-mls
        container_name: mr-owlf-mls
        # restart: always
        depends_on:
            - cassandra-node-01
        environment:
            MR_OWLF_ENV: "DOCKER"
            MR_OWLF_LOG_FILE: "/usr/src/mr-owlf/logs/mr-owlf-mls.log"
            MR_OWLF_DB_CONN: cassandra-node-01
            MR_OWLF_DB_PORT: "9042"
            MR_OWLF_DB_KEYSPACE: "mr_owlf_ks"
            MR_OWLF_CLF_FILE: "/usr/src/mr-owlf/shared/clf.pkl"
        volumes:
            - ./.shared:/usr/src/mr-owlf/shared/
            - ./.shared/logs:/usr/src/mr-owlf/logs/

    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
    #  API
    # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~= 
    api:
        image: mr-owlf-api
        container_name: mr-owlf-api
        restart: always
        ports:
            - 80:80
        environment:
            MR_OWLF_CLF_FILE: "/usr/src/mr-owlf/shared/clf.pkl"
        volumes:
            - ./.shared:/usr/src/mr-owlf/shared/
 

