FROM python:3

WORKDIR /opt/mr-owlf-mls

COPY requirements.txt ./
COPY mr_owlf_mls ./mr_owlf_mls
COPY *.py ./

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

CMD sleep ${VARIABLE:=0} && python ./main.py
